USE [master]
GO
/****** Object:  Database [FredrikHotell]    Script Date: 2023-01-01 19:40:39 ******/
CREATE DATABASE [FredrikHotell]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FredrikHotell', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FredrikHotell.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FredrikHotell_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FredrikHotell_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FredrikHotell] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FredrikHotell].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FredrikHotell] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FredrikHotell] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FredrikHotell] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FredrikHotell] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FredrikHotell] SET ARITHABORT OFF 
GO
ALTER DATABASE [FredrikHotell] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FredrikHotell] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FredrikHotell] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FredrikHotell] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FredrikHotell] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FredrikHotell] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FredrikHotell] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FredrikHotell] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FredrikHotell] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FredrikHotell] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FredrikHotell] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FredrikHotell] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FredrikHotell] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FredrikHotell] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FredrikHotell] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FredrikHotell] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FredrikHotell] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FredrikHotell] SET RECOVERY FULL 
GO
ALTER DATABASE [FredrikHotell] SET  MULTI_USER 
GO
ALTER DATABASE [FredrikHotell] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FredrikHotell] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FredrikHotell] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FredrikHotell] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FredrikHotell] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FredrikHotell] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'FredrikHotell', N'ON'
GO
ALTER DATABASE [FredrikHotell] SET QUERY_STORE = ON
GO
ALTER DATABASE [FredrikHotell] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FredrikHotell]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 2023-01-01 19:40:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Bookings]    Script Date: 2023-01-01 19:40:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bookings](
	[BookingID] [int] IDENTITY(1,1) NOT NULL,
	[StartDate] [datetime2](7) NOT NULL,
	[EndDate] [datetime2](7) NOT NULL,
	[BookingDate] [datetime2](7) NOT NULL,
	[RoomID] [int] NOT NULL,
	[CustomerID] [int] NOT NULL,
 CONSTRAINT [PK_Bookings] PRIMARY KEY CLUSTERED 
(
	[BookingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 2023-01-01 19:40:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](max) NOT NULL,
	[LastName] [nvarchar](max) NOT NULL,
	[PhoneNumber] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rooms]    Script Date: 2023-01-01 19:40:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rooms](
	[RoomID] [int] IDENTITY(1,1) NOT NULL,
	[RoomSize] [int] NOT NULL,
	[RoomType] [nvarchar](max) NOT NULL,
	[RoomPrice] [int] NOT NULL,
	[AmountOfBeds] [int] NOT NULL,
 CONSTRAINT [PK_Rooms] PRIMARY KEY CLUSTERED 
(
	[RoomID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Bookings_CustomerID]    Script Date: 2023-01-01 19:40:40 ******/
CREATE NONCLUSTERED INDEX [IX_Bookings_CustomerID] ON [dbo].[Bookings]
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Bookings_RoomID]    Script Date: 2023-01-01 19:40:40 ******/
CREATE NONCLUSTERED INDEX [IX_Bookings_RoomID] ON [dbo].[Bookings]
(
	[RoomID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bookings]  WITH CHECK ADD  CONSTRAINT [FK_Bookings_Customers_CustomerID] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customers] ([CustomerID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Bookings] CHECK CONSTRAINT [FK_Bookings_Customers_CustomerID]
GO
ALTER TABLE [dbo].[Bookings]  WITH CHECK ADD  CONSTRAINT [FK_Bookings_Rooms_RoomID] FOREIGN KEY([RoomID])
REFERENCES [dbo].[Rooms] ([RoomID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Bookings] CHECK CONSTRAINT [FK_Bookings_Rooms_RoomID]
GO
USE [master]
GO
ALTER DATABASE [FredrikHotell] SET  READ_WRITE 
GO